### ISSUE TITLE
Improving on-boarding process

### ISSUE THREAD

**Issue by romainsassareu** [Nosto/nosto-prestashop-module#45]
Merchants are all alone during two crucial steps of the on-boarding : 

1/ When they have to select the account (language account) :

![well installed](https://cloud.githubusercontent.com/assets/10031826/5249408/4ae91102-798b-11e4-90b8-6fd93f9deede.jpg)

Problem : 
- some merchants won't even noticed there is the dropdown menu
- some merchants won't realize they have to pick the correct language account to synch to Nosto
- No way to have access to Support content (no link, embed video, ...)

2/ When they have to pick if either they have an account or not : 

![well_installed_2](https://cloud.githubusercontent.com/assets/10031826/5249194/de3030e6-7989-11e4-91a6-50653fe5fe69.jpg)

Problem : 
- some merchants won't understand they have to create one nosto account per language account.
- No way to have access to Support content (no link, embed video, ...)

Let's get inspired with what Google is doing when you first connect to your new shiny Gmail account : 

![screencapture-accounts-google-com-b-1-signupdone](https://cloud.githubusercontent.com/assets/10031826/5249375/1c1cff46-798b-11e4-8772-0204633e77ab.png)
![screencapture-mail-google-com-mail-u-1-1](https://cloud.githubusercontent.com/assets/10031826/5249377/1c1ed5e6-798b-11e4-803e-308c1d54060d.png)
![screencapture-mail-google-com-mail-u-1](https://cloud.githubusercontent.com/assets/10031826/5249443/95d7841e-798b-11e4-866d-e499c2768f24.jpg)

Let's liaise with Tuukkaa & Dominik on that !

**Comment by mridang** [comment]
Will be fixed with the new UI.
