### ISSUE TITLE
Raidlight - No orders tracked 

### ISSUE THREAD

**Issue by romainsassareu** [Nosto/nosto-prestashop-module#52]
http://www.raidlight.com/en/

They have re-added the hooks missing but we still don't track the orders at all : https://my.nosto.com/admin/global/orders/prestashop-5f50bd1e

I let you dig and i'll get back to the agency once we have a solution for that. In the meantime, if you need some logs or other info. I can ask the agency, they even asked me if we want an access to their Prestashop back-end. 

How do you feel ?

**Comment by mridang** [comment]
Issue seems to have been attributed to missing hooks. This seems to have been resolved.

**Comment by romainsassareu** [comment]
Looks like it's something else. 

Here is what the dev at the agency did : 

He modified a piece of code that is catching the Nosto account ID to display the tagging on the order confirmation page.

There was apparently the same issue when the status of orders change. He then changed the  NostoTaggingAccount::getName() method to catch the account ID (hardcoding).

He is also saying that the issue was there every time the status of orders was modified. The request seems to be sent via API but nothing moves in the stat.

He is also asking if we have anything related to cache duration ?

**Comment by kryysler** [comment]
Any chance of seeing the actual changes they did to the code?

**Comment by romainsassareu** [comment]
I'll ask or that and keep you posted.
